services:
  server:
    build: ./server
    container_name: server
    restart: always
    command: >
      sh -c "npm run dev"
    ports:
      - "3000:3000"
    networks:
      - mern-network

  client:
    build: ./client
    container_name: client
    restart: always
    command: >
      sh -c "npm run dev"
    ports:
      - "5173:5173"
    networks:
      - mern-network

  ml.server:
    build: ./ml.server
    container_name: ml-server
    restart: always
    command: >
      sh -c "python3 flaskr/app.py"
    ports:
      - "5000:5000"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
